### ISSUE TITLE
Better native library loading mechanism

### ISSUE THREAD

**Issue by haraldsteinlechner** [aardvark-platform/aardvark.base#36]
- currently, we unpack native dependencies to the current working directory. native dependencies then get loaded from there. this is suboptimal since we need write permissions in the executable folder.
- we could load native assemblies from memory blobs. affected files: src/aardvark.base/Introspection/Introspection.cs

**Comment by jackfoxy** [comment]
I experienced this problem, or similar. I created a project from the "first implementation" in the article https://rawgit.com/wiki/aardvark-platform/aardvark.docs/docs/media/Elmish.html 

I had to change the open statements in the entry point somewhat from the article in order to build.

```
open Aardvark.Base
open Aardvark.Base.Incremental
open Aardvark.Application
open Aardvark.Application.Slim
open Aardvark.SceneGraph
```

Builds, but missing DLL at runtime.

```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'glvm' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Aardvark.Rendering.GL.GLVM.hglCleanup(IntPtr ctx)
   at Aardvark.Rendering.GL.ContextHandle.MakeCurrent() in C:\- Data\aardvark.rendering\src\Aardvark.Rendering.GL\Core\ContextHandles.fs:line 100
   at <StartupCode$Aardvark-Rendering-GL>.$Context.get_ResourceLock@285.Invoke(ContextToken x) in C:\- Data\aardvark.rendering\src\Aardvark.Rendering.GL\Core\Context.fs:line 298
   at Aardvark.Rendering.GL.ContextToken.Obtain() in C:\- Data\aardvark.rendering\src\Aardvark.Rendering.GL\Core\Context.fs:line 30
   at Aardvark.Rendering.GL.ContextToken..ctor(FSharpFunc`2 obtain, FSharpFunc`2 release) in C:\- Data\aardvark.rendering\src\Aardvark.Rendering.GL\Core\Context.fs:line 14
   at Aardvark.Rendering.GL.Context.get_ResourceLock() in C:\- Data\aardvark.rendering\src\Aardvark.Rendering.GL\Core\Context.fs:line 284
   at <StartupCode$Aardvark-Rendering-GL>.$ResourceManager.bufferMemory@24.Invoke(IntPtr size) in C:\- Data\aardvark.rendering\src\Aardvark.Rendering.GL\Management\ResourceManager.fs:line 24
   at Aardvark.Base.Management.ChunkedMemoryManager`1..ctor(Memory`1 mem, IntPtr chunkSize) in C:\- Data\aardvark.rendering\src\Aardvark.Base.Rendering\Runtime.fs:line 449
   at Aardvark.Rendering.GL.UniformBufferManager..ctor(Context ctx) in C:\- Data\aardvark.rendering\src\Aardvark.Rendering.GL\Management\ResourceManager.fs:line 47
   at Aardvark.Rendering.GL.ResourceManager..ctor(FSharpOption`1 parent, Context ctx, FSharpOption`1 renderTaskInfo, Boolean shareTextures, Boolean shareBuffers) in C:\- Data\aardvark.rendering\src\Aardvark.Rendering.GL\Management\ResourceManager.fs:line 280
   at Aardvark.Rendering.GL.Runtime.set_Context(Context c) in C:\- Data\aardvark.rendering\src\Aardvark.Rendering.GL\Runtime\Runtime.fs:line 105
   at Aardvark.Application.Slim.OpenGlApplication..ctor(Boolean forceNvidia, Boolean enableDebug) in C:\- Data\aardvark.rendering\src\Application\Aardvark.Application.Slim.GL\Application.fs:line 17
   at Program.main(String[] argv) in C:\Users\jackf\GitRepos\AardvarkSandBox\src\DslFirstImplementation\Program.fs:line 17
```

**Comment by krauthaufen** [comment]
I'll look into that tomorrow. Maybe we should just unpack the libs to some temp-folder and load them directly after extraction. 
However I'll hqve to check whether or not DllImports will work when loading libs via fully qualified paths.

**Comment by krauthaufen** [comment]
should be resolved via https://github.com/aardvark-platform/aardvark.base/commit/b3f181933464592e8c06395acca91d6eb93413cc (package versions 4.5.15)

**Comment by krauthaufen** [comment]
rendering/media working

**Comment by jackfoxy** [comment]
Updating to Base 4.5.15, I still have the same error reported above from Aardvark.Rendering.GL 4.11.7.
 
I'll try looking deeper into the Aardvark.Rendering code sometime.
https://github.com/aardvark-platform/aardvark.rendering/blob/master/src/Aardvark.Rendering.GL/Core/Context.fs
does not show me any obvious problem at line 100.
 
In any case, it seems the problem is not in this project. If I cannot make progress I will open an issue in Aardvark.Rendering.

**Comment by krauthaufen** [comment]
hey, are you sure you're using the newest Aardvark.Base package?
sometimes VS/MSBuild tend to use old dlls due to some caching problems.

Is it still complaining about not finding glvm.dll?

**Comment by jackfoxy** [comment]
@krauthaufen executing in debug I get a different stack trace, which I believe is the correct stack trace and points to a C++ module in Aardvark.Rendering. So I think it is a different issue than the one tracked here.

```
at Aardvark.Rendering.GL.GLVM.hglCleanup(IntPtr ctx)
at Aardvark.Rendering.GL.ContextHandle.MakeCurrent()
at <StartupCode$Aardvark-Rendering-GL>.$Context.get_ResourceLock@285.Invoke(ContextToken x)
at Aardvark.Rendering.GL.ContextToken.Obtain()
at Aardvark.Rendering.GL.ContextToken..ctor(FSharpFunc`2 obtain, FSharpFunc`2 release)
at Aardvark.Rendering.GL.Context.get_ResourceLock()
at <StartupCode$Aardvark-Rendering-GL>.$ResourceManager.bufferMemory@24.Invoke(IntPtr size)
at Aardvark.Base.Management.ChunkedMemoryManager`1..ctor(Memory`1 mem, IntPtr chunkSize)
at Aardvark.Rendering.GL.UniformBufferManager..ctor(Context ctx)
at Aardvark.Rendering.GL.ResourceManager..ctor(FSharpOption`1 parent, Context ctx, FSharpOption`1 renderTaskInfo, Boolean shareTextures, Boolean shareBuffers)
at Aardvark.Rendering.GL.Runtime.set_Context(Context c)
at Aardvark.Application.Slim.OpenGlApplication..ctor(Boolean forceNvidia, Boolean enableDebug)
at Program.main(String[] argv) in C:\\Users\\jackf\\GitRepos\\AardvarkSandBox\\src\\DslFirstImplementation\\Program.fs:line 17
```

**Comment by krauthaufen** [comment]
okay, that indeed seems to be something different...
could you open an issue in aardvark.rendering for that?
